# Generated by Django 2.0.6 on 2018-06-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantastical_things', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
