# Generated by Django 2.0.6 on 2018-06-23 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantastical_things', '0002_task_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='cardlist',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='name',
            new_name='title',
        ),
    ]
