# Generated by Django 2.0.6 on 2018-06-24 20:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fantastical_things', '0003_auto_20180623_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='users',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='all_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
