# Generated by Django 2.0.6 on 2018-06-24 21:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fantastical_things', '0004_board_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='users',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='card_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cardlist',
            name='users',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='cardlist_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='users',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='task_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='board',
            name='users',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='board_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
