# Generated by Django 2.0.6 on 2018-06-24 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantastical_things', '0005_auto_20180624_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='fantastical_things.Card'),
        ),
    ]
