# Generated by Django 2.0.6 on 2018-06-25 07:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantastical_things', '0008_auto_20180625_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='begin_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 25, 7, 44, 15, 357301)),
        ),
        migrations.AlterField(
            model_name='card',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 25, 7, 44, 15, 357321)),
        ),
    ]
