# Generated by Django 2.0.6 on 2018-06-26 16:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantastical_things', '0009_auto_20180625_0744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='parent',
        ),
        migrations.AlterField(
            model_name='card',
            name='begin_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='card',
            name='deadline',
            field=models.DateTimeField(default=None),
        ),
    ]
