# Generated by Django 2.0.6 on 2018-06-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantastical_things', '0010_auto_20180626_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='deadline',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
