# Generated by Django 2.0.6 on 2018-06-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantastical_things', '0011_auto_20180626_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
        migrations.AlterField(
            model_name='board',
            name='title',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='card',
            name='days',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='hours',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='minutes',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='months',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='seconds',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='title',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='card',
            name='years',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='cardlist',
            name='title',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
