# Generated by Django 2.0.6 on 2018-06-27 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantastical_things', '0013_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='days',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='hours',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='minutes',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='months',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='seconds',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='years',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
