# Generated by Django 2.0.6 on 2018-06-27 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantastical_things', '0014_auto_20180627_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='days',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='card',
            name='hours',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='card',
            name='minutes',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='card',
            name='months',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='card',
            name='seconds',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='card',
            name='years',
            field=models.SmallIntegerField(default=0),
        ),
    ]
